version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db2
    environment:  
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=battlefield2042_postgres
      - POSTGRES_USER=david_postgres
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: david.hb@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: viscabarsa
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: